### ISSUE TITLE
 Error: invalid device function

### ISSUE THREAD

**Issue by shawangyi123** [niuzhiheng/caffe#1]
I have some errors like this when running the train_lenet.bat with GPU. How to handle those problems?
... im2col.cu:49] Check failed. Error == cudaSuccess (8 vs.0) invalid device function

My GPU is GTX650.
I can run both the NVIDIA-bundled samples and train_lenet.bat with CPU successfully.

**Comment by niuzhiheng** [comment]
According to your error code 8, it says:

```
/**
 * The requested device function does not exist or is not compiled for the
 * proper device architecture.
 */
cudaErrorInvalidDeviceFunction        =      8,
```

From Wikipedia, your device GTX650 got CUDA Compute Capability 3.0 whereas I think in my case it was set to **Capability 3.5**. You may change this in `Properties->CUDA C/C++->device->Code Generation`.

From: `compute_35,sm_35` to `compute_30,sm_30`.

**Comment by shawangyi123** [comment]
Thank you so much. I successfully train MNIST dataset.
Do you know what is the way to compile MATLAB wrappers and how to make matcaffe.
I am a newbie, I directly mex matcaffe.cpp in MATLAB,  it doesn't work.

**Comment by niuzhiheng** [comment]
Python and Matlab wrappers are currently not supported for this windows porting.
