### ISSUE TITLE
how to run imagenet example in windows

### ISSUE THREAD

**Issue by liguanbin** [niuzhiheng/caffe#10]
hi, thanks your help, I have successfully run mnist in my computer. I am a newbie and do not know how to do next. My ultimate goal is to train my own model using caffe, I do not know how to prepare the training data of the type of caffe needed. can i try other examples in windows, e.g. imagenet? could you give me some suggestion on how to get familiar with caffe? Really thanks a lot!

**Comment by niuzhiheng** [comment]
Please refer to the [official docs](https://github.com/BVLC/caffe/tree/master/docs). For imagenet, you may take a look at [this](https://github.com/BVLC/caffe/blob/master/docs/imagenet_training.md).

The procedures are more or less the same. But you have to do them on the Windows environment. For example, to configure a path in *.prototxt, you need to use `C:\\path\\to\\your\\file` instead of `/path/to/your/file` on Linux. Please notice the double back slash.

**Comment by liguanbin** [comment]
thanks a lot. how can I create the imagenet leveldb inputs in windows? do I need to generate a "convert_imageset.bin" or "convert_imageset.exe" first in windows ?

**Comment by niuzhiheng** [comment]
Yes, you are right. Change correspondingly in the `MainCaller.cpp` file.

**Comment by liguanbin** [comment]
Got it! Thanks a lot. You really helps me a lot. 
I wanna do 2 class classification using caffe. I have lots of samples, say with 100 dimensions and each sample has a label, say 0 or 1. how can i get start to do this job in windows using caffe? Do i need to read the code first? how can I convert my feature data into the type caffe wanted? Thanks again!

**Comment by marc40000** [comment]
I'm trying to do something similiar I guess. I'm jsut confused with your "100 dimensions". I haven't figured it out yet, but I figured out a little bit so I'll post that:

I created two Folders containing Images of the two classes. One Folder is for Training und one for Validation. You also Need 2 list files, that contain all the filenames in each Directory followed by a class. One of them Looks like this for me

Banane-201020047719.jpg 1
banane.jpg 1
banane1.jpg 1
Banane2.jpg 1
bananen.jpg 1
Bijoy_Keyboard_image.jpg 0
Devanagari_INSCRIPT_Keyboard.jpg 0
mac_mechanical_keyboard_2.jpg 0
Pasted%20Graphic%202.jpg 0
QWERTY_keyboard.jpg 0

Yeah, I try to distingish between Keyboards and bananas. ;) 
Having this, you can call convert_imageset twice for each set of Folder/listfile. This creates two leveldb-directories which contain all you Images and their classes. Train_net.exe wants it that way.
Afterwards, depending on the prototxt files which define the nn to Train or how it gets trained - I'm actually not so sure about that - you have to genereate the Image mean. The lenet/mnist prototxt files don't use it but the imagenet ones do. You can compute the Image means with compute_image_mean.exe . It just takes a leveldb as Input and creates an imagemean file.
Then you can "create your proto-files" and call Train_net.exe on them. 
I just tried modifying lenet/mnist and imagenet ones. lenet/mnist runs much faster than imagenet, but both produce garbage for me so far. :/
So I hope this was somehow helpfull. If you figure this out, please let me know how to do it :)
