### ISSUE TITLE
extract_features.cpp compile fixes

### ISSUE THREAD

**Issue by marc40000** [niuzhiheng/caffe#12]
3 Things:
- snprintf => _snprintf
- typedef unsigned int uint; at the top
- shared_ptr to boost::shared_ptr

Maybe I should check out how to do pull requests ...

**Comment by niuzhiheng** [comment]
Thank you for your feedback. I am very glad to receive your PR.

Please refer to the paragraph of **Shelhamer's “life of a branch in four acts”** from official [readme](https://github.com/BVLC/caffe/blob/master/README.md) to see how you may do that.

**Comment by niuzhiheng** [comment]
Solved in abfee75a2494092e149489a29fc8f8147ec38b38

**Comment by marc40000** [comment]
Ok. If there is a next time I'll figure out the pr before posting an issue ;)
