### ISSUE TITLE
Missing libgfortran-3.dll

### ISSUE THREAD

**Issue by marc40000** [niuzhiheng/caffe#13]
After compilation I now get a "The program can't start because libgfortran-3.dll is missing from your Computer"-message when I try to run train_net.exe . Strangely, compute_image_mean and conver_imageset work.
I did a fresh git clone on another pc. I also used newer precompiled dependencies. Before I used dependency-20140514.7z, now I'm using dependency-20140624.7z.
The old one used libgslcblas-0.dll, the new libopenblas.dll . so maybe something is odd there?

**Comment by marc40000** [comment]
I figured out that dll is part of mingw. I also needed the following dlls to run train_net.exe:

libgcc_s_seh-1.dll
libquadmath-0.dll
libwinpthread-1.dll

**Comment by niuzhiheng** [comment]
Those files are packed to the 7z file now. Thank you.
