### ISSUE TITLE
Merging the latest version from caffe master

### ISSUE THREAD

**Issue by shaile7** [niuzhiheng/caffe#14]
Hi,

I have downloaded your version of caffe for Windows and it seems to work fine. Thanks.

It seems that the master version progresses, so there may be a need to merge with its latest version from time to time.
Are you planning to maintain the code up to date ? 
If I want to merge it myself, then, except for copying the changed .cpp .cc .h .hpp files, is there something else I should do ?

Thanks,
Shaile.

**Comment by niuzhiheng** [comment]
Sorry, I do not have much time to keep updating this windows version unless there is a major release or many requests from others. @shaile7 You may try to rebase the latest master branch onto current windows branch and solve all the conflicts manually.

**Comment by shaile7** [comment]
Ok, thanks.
