### ISSUE TITLE
how I transfer my data to format of caffe needed in windows?

### ISSUE THREAD

**Issue by xinyaojiejie** [niuzhiheng/caffe#15]
I have wrote all the training files' names  and labels in a text named train.txt, as following format:
F:\cnn training\Sample001\img001-00001.jpg 1
F:\cnn training\Sample001\img001-00002.jpg 1
F:\cnn training\Sample002\img001-00003.jpg 2
F:\cnn training\Sample001\img001-00004.jpg 2
there are 62 classes. I also got convert_imageset.exe by mainCaller.
Then I start command line windows and enter following command:
convert_imageset f:\caffe-windows\mydata\train.txt f:\caffe-windows\to\train_leveldb
but it seemed that no files are produced, there only have following prompt:
  convert_imageset ROOTFOLDER/LISTFILE DB_NAME RANDOM_SHUFFAL_DATA[0 or 1] 

what' s wrong? Could anybody give me some suggetion? Thank you!

**Comment by xuzhm** [comment]
xinyaojiejie,i think you are Chinese, so i want to answer your question in 中文。你的命令行应该是这样的“   convert_imageset    这儿还要写个你图片文件夹的路径      f:\caffe-windows\mydata\train.txt f:\caffe-windows\to\train_leveldb  ”

**Comment by xinyaojiejie** [comment]
Thank you, Yes I am Chinese. I have put all the training images in f:\cnn directory,so  should I use the command as following:
convert_imageset  f:\cnn/  f:\caffe-windows\mydata\train.txt  f:\caffe-windows\to\train_leveldb

where f:\cnn is the directory that I have put all my images in,is that ok? but it also has some problems. I wonder that how should I write in train.txt. Dose the directory in this text file has the following format :
F:\cnn training\Sample001\img001-00001.jpg 1
F:\cnn training\Sample001\img001-00002.jpg 1
F:\cnn training\Sample002\img001-00003.jpg 2
F:\cnn training\Sample001\img001-00004.jpg 2
       or should write as double backslash, for example:
F:\\cnn training\\Sample001\\img001-00001.jpg 1
F:\\cnn training\\Sample001\\img001-00002.jpg 1
F:\\cnn training\\Sample002\\img001-00003.jpg 2
F:\\cnn training\\Sample001\\img001-00004.jpg 2
      Anybody are welcome to write me directly to help me solve the problem, my mail address is 
xinyaojiejie@gmail.com. Thank you.

**Comment by marc40000** [comment]
I'm not sure if you can put pathnames in the list files. But if you can, I bet the spaces in your pathname screw it up.

I have no path names in my list files. You tell convert_imageset the path to your Images as a cmdline Parameter. My list files look like this:

Banane-201020047719.jpg 1
banane.jpg 1
banane1.jpg 1
Banane2.jpg 1
bananen.jpg 1
Bijoy_Keyboard_image.jpg 0
Devanagari_INSCRIPT_Keyboard.jpg 0
mac_mechanical_keyboard_2.jpg 0
Pasted%20Graphic%202.jpg 0
QWERTY_keyboard.jpg 0

You also should take care not to have spaces in your filenames. I'm not sure if convert_imageset handles that correctly.

**Comment by xinyaojiejie** [comment]
I have solved the problem yet. I should write relative path rather than full path in txt file. 
Now every thing dose work.
