### ISSUE TITLE
how can i train ImageNet on windows?

### ISSUE THREAD

**Issue by frischzenger** [niuzhiheng/caffe#17]
first, I can't find the convert_imageset.bin, and on the windows i can't run the *.sh script files. 
so I 've used the convert_imageset.cpp build up the convert_imageset.exe, and the I create a batch file so that can run on windows. it looks like this:

```
echo "Creating leveldb..."

SET GLOG_logtostderr=1 
    "..//..//bin//convert_imageset.exe"  ".//LUJIN//to//imagenet//train//"  "..//..//data//ilsvrc12//train.txt"     "imagenet_train_leveldb"    0
echo "Done."
pause
```

the content of train.txt is:
n01443537/n01443537_2.JPEG 1
n01443537/n01443537_129.JPEG 1
and the correspond picture in the folder "./LUJIN/to/imagenet/train/"
when there only one picture in the folder, it's ok! but more than one picture it will be error happend, 
the error in the convert_imageset.cpp line 88 is:
CHECK_EQ(data.size(), data_size) << "Incorrect data field size "
that is data.size not equal to data_size, 

I guess the reason is that all the picture is not the same size, but how can i crop the picture size to the fixed size? and what size will be the best size?
thanks for your help!

**Comment by frischzenger** [comment]
secondly, i read the documents from 
BVLC/caffe, i read the code like this:
for name in /path/to/imagenet/val/*.JPEG; do
    convert -resize 256x256! $name $name
done

how can i get the convert.exe ?

**Comment by niuzhiheng** [comment]
It is [**ImageMagick**](http://sourceforge.net/projects/imagemagick/) you have to use.

**Comment by frischzenger** [comment]
thanks for your reply, I am a newbie to mapReduce, is there any documents to help to build up the resize process steps? and i can't find any documents about how to use mincepie, can anyone help me?
thanks!

**Comment by niuzhiheng** [comment]
For general discussions which are irrelevant to windows porting, I suggest you post the questions on the [official Caffe website](https://github.com/BVLC/caffe) from where this fork derived. You may get more valuable help instantly from there.
