### ISSUE TITLE
Issues of assertion for computing images means

### ISSUE THREAD

**Issue by xinyaojiejie** [niuzhiheng/caffe#18]
when I use compute_images_mean to compute mean of images, It throw an assertion as following:

Assertion failed: dummy_versions_.next==&dummy_versions_. file .db\version_set.cc, line 803

Dose anybody give me some suggestion on it or anybody help me compute my dataset's mean?

**Comment by niuzhiheng** [comment]
Did you figure it out by yourself?

**Comment by xinyaojiejie** [comment]
Somebody told me that this exception has nothing to do with the final result. Though the exception is throw,  the image mean was still generated and can be used it without anything visibly going wrong.

**Comment by niuzhiheng** [comment]
Thank you for your feedback.
