### ISSUE TITLE
train_net says "The handle is invalid"

### ISSUE THREAD

**Issue by marc40000** [niuzhiheng/caffe#2]
Hi !

I'm not sure why I get this message, so I describe what I did.

I'm trying to use caffe on a test dataset I created. It contains of Images containing two types of things. I scalled all Images to 256^2 jpgs.

I put all Images in a Directory. I created a text files containing the filesnames of the Images followed by a 0 or a 1, depending on the class I want them in. Is this the correct?

I execute conver_imageset on that directory with Shuffle set to 1. It creates a leveldb-Directory.

Afterwards, I execute compute_image_mean of the leveldb. I'm not sure if this is needed. I see the imagenet_.prototxt reference this while the lenet_.prototxt don't reference an Image_mean file.

I copied the imagenet_solver.prototxt, imagenet_train.prototxt and imagenet_val.prototxt and changed the references to the leveldb and the imagemean-file. Afterwards, when I call Train_net with the imagenet_train.prototxt, I get the error message 

F0620 02:05:50.904736 11536 data_layer.cpp:148] Check failed: status.ok() Failed
 to open leveldb testpicsdb
IO error: testpicsdb\MANIFEST-000013: The handle is invalid.
**\* Check failure stack trace: ***

Also, I tried modifying the lenet_prototxt-files accoringly and tried using them with train_net. The result is the same. But, if I call Train_net on the unmodified lenet_prototxt files referencing the mnist-leveldb, it works. So I assume somehow it's my leveldb. But what's wrong with it?

For completeness, I uploaded the testimages as well as the list-file, generated leveldb, imagemean, *.prototxt if you want to take a look,.
here http://www.transmogrifier.de/temp/testpics.7z .

Thx
   marc

**Comment by niuzhiheng** [comment]
@marc40000 Did you create your level-db from Linux? If so, I am afraid it is not gonna work. 
level-db created from windows is working fine for Caffe in Linux, but not the another way around.

**Comment by marc40000** [comment]
Thx for your answer :)

I did everything on Windows.

Maybe it's the way I compiled the binaries? I'm not sure about that. In MainCaller.cpp there were 4 lines:

#include "../../tools/train_net.cpp"
//#include "../../tools/net_speed_benchmark.cpp"
//#include "../../tools/finetune_net.cpp"
//#include "../../tools/test_net.cpp"

I also needed convert_imageset and compute_image_mean. So I added lines for those:

//#include "../../tools/train_net.cpp"
//#include "../../tools/net_speed_benchmark.cpp"
//#include "../../tools/finetune_net.cpp"
//#include "../../tools/test_net.cpp"

#include "../../tools/convert_imageset.cpp"
//#include "../../tools/compute_image_mean.cpp"

and uncommented the two one after another, compiled and renamed the generated MainCaller.exe to convert_imageset.exe and compute_image_mean.cpp

The strange Thing is, compute_image_mean also needs the leveldb and it has no problem using it as it seems.

Any suggestions what I could try to figure it out?

**Comment by niuzhiheng** [comment]
I have download and checked your configuration. It turns out that you use the same leveldb for both training and testing. Please note google leveldb is not inter-process concurrent, it is only inter-thread concurrent. That means you can not open it twice.

@marc40000 When I did this, Caffe works fine. Duplicate `testpicsdb` and rename the copy as `trainpicsdb` for example. Change correspondingly in  `.prototxt`.

**Comment by marc40000** [comment]
Oh I didn't realize they had to be different dbs. It runs if I duplicate the leveldb as you suggested. Thx :)
