### ISSUE TITLE
error MSB3073: 命令“set origin_dir=Í%

### ISSUE THREAD

**Issue by shiorioxy** [niuzhiheng/caffe#22]
When I compiling the project, VS return the error message:
Why? and what I can do? Thank you!

错误  1   error MSB3073: 命令“set origin_dir=Í%
cd ../../
"./scripts/GeneratePB.bat"
cd %origin_dir%
:VCEnd”已退出，代码为 1。 C:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0\V120\Microsoft.CppCommon.targets  122 5   MainCaller

**Comment by niuzhiheng** [comment]
Please check if `./scripts/GeneratePB.bat` exists.
