### ISSUE TITLE
Vs2012 compiler will halt for a long time after displaying "1>  caffe.pb.h remains the same as before" 

### ISSUE THREAD

**Issue by AlexXieHzZj** [niuzhiheng/caffe#3]
1>  caffe.pb.h remains the same as before

vs2012 compiler will stop for about 30 minutes and then it will continue to compile. I've test on several computer on windows 7 and visual studio 2012, the problem remains the same.

**Comment by niuzhiheng** [comment]
For the first time of compilation, it usually takes quite a long time. However 30 minutes seem to be too long. But it should be much faster if you build again when several files changed. But if you come up to rebuild again, it will take long time again.

For this issue, I did not find any solution yet. If you have any ideas about it, please kindly let me know. Thank you.

**Comment by marc40000** [comment]
Not having a solution for your issue, but I also wondered at that point what was happening. But it turned out, as niuzhiheng, says, it just took a while and then it continued. A minute or so. But not close to 30 minutes. I also used vs 2012 for compilation just yesterday. (My OS is Win 8.1 64 bit. I don't think that could be the reason though.)

**Comment by AlexXieHzZj** [comment]
I cleaned the project and  enabled Timing Logging by setting “Tools/Options/Projects and Solutions/VC++ Project Settings/Build Timings” = “Yes” or raise the verbosity of the build to “Diagnostics” from “Tools/Options/Project and Solutions/Build and Run/MSBuild project build output verbosity”. Here are some Diagnostics outputs:
Project Performance Summary:
1>    1623688 ms  D:\Dev\caffe\caffe-window-git\build\MSVC\MainBuilder.vcxproj   1 calls
1>              1623688 ms  rebuild                                    1 calls
1>
1>Target Performance Summary:
1>        0 ms  ComputeMIDLGeneratedCompileInputs    1 calls
...............
1>    105928 ms  ClCompile                               1 calls
1>    434458 ms  CudaBuild                               23 calls
1>    1079991 ms  AddCudaCompileDeps                     23 calls
1>Task Performance Summary:
1>        0 ms  ReadLinesFromFile                        2 calls
...............
1>    105910 ms   CL                                     1 calls
1>    434057 ms   CudaCompile                            23 calls
1>    1079071 ms  GenerateDeps                           23 calls
1>Build succeeded.
1>
1>Time Elapsed 00:27:03.68
========== Rebuild All: 1 succeeded, 0 failed, 0 skipped ==========

That's my home computer( Win 7 64bit , Vs 2010 ,and CUDA 6.0),  CPU is quad-core Xeon E31230. Video card is GTS 450. 
Any options to disable CUDA compiler to Indexing and generating depends? By now I have to remember never clean the project.   :=(

**Comment by niuzhiheng** [comment]
@AlexXieHzZj Thank you very much for your profiling with the compiling time. It really takes such a long time for Indexing and generating depends. I do not yet have a solution for now.

**Comment by marc40000** [comment]
FYI: I just did a fresh clone on another pc and it took about 3 min to compile altogether. Thought this might be of some interest.
