### ISSUE TITLE
Adding a layer - updating caffe.proto

### ISSUE THREAD

**Issue by benjaminklein** [niuzhiheng/caffe#30]
Hi,

I'm trying to add a layer. In linux, I would change caffe.proto, and then caffe.pb.h and the other effected files would have been updated automatically. 

I tried doing the same here (changing caffe.proto - adding a new layer), but caffe.pb.h does not update and therefore I can't use my new layer.

Did I miss something? Could anyone explain how caffe.proto is being converted on windows? 

Thanks!

**Comment by niuzhiheng** [comment]
You have to delete the file manually so that it can be regenerated.

**Comment by benjaminklein** [comment]
Thank you! It's working.
