### ISSUE TITLE
Problem Building on Windows 8.1 x64

### ISSUE THREAD

**Issue by andreteixeiralopes** [niuzhiheng/caffe#31]
Hi,
I Followed the installations instructions and when I Build the Project, after few minutes VS 2012 give the following error:

1>  ptxas C:/Users/ANDR~1/AppData/Local/Temp/tmpxft_00002c90_00000000-13_bnll_layer.compute_20.ptx, line 1709; fatal   : Parsing error near '-': syntax error
1>  ptxas fatal   : Ptx assembly aborted due to errors
1>  bnll_layer.cu
1>C:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0\V110\BuildCustomizations\CUDA 6.5.targets(593,9): error MSB3721: The command ""C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v6.5\bin\nvcc.exe" -gencode=arch=compute_20,code=\"sm_20,compute_20\" -gencode=arch=compute_30,code=\"sm_30,compute_30\" -gencode=arch=compute_35,code=\"sm_35,compute_35\" -gencode=arch=compute_50,code=\"sm_50,compute_50\" --use-local-env --cl-version 2012 -ccbin "C:\Program Files (x86)\Microsoft Visual Studio 11.0\VC\bin\x86_amd64"  -I../../3rdparty/include -I../../3rdparty/include/eigen3/Eigen -I../../src -I../../include -I"C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v6.5\include" -I"C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v6.5\include"  -G   --keep-dir x64\Debug -maxrregcount=0  --machine 64 --compile -cudart static  -g   -D_VARIADIC_MAX=10 -DWIN32 -D_DEBUG -D_CONSOLE -D_MBCS -Xcompiler "/EHsc /W3 /nologo /Od /Zi /RTC1 /MDd  " -o Debug\bnll_layer.cu.obj "C:\Users\André\Downloads\caffe-windows\caffe-windows\src\caffe\layers\bnll_layer.cu"" exited with code 255.

I'm Using a Windows 8.1, 64 bits, Visual Studio 2012, CUDA Framework v6.5, and I Buil the Project using the x64 architecture 

Anyone ever had this error?

Thanks,
André

**Comment by niuzhiheng** [comment]
Can you please try to build in a directory with all ASCII characters? I am afraid the nvcc may have troubles dealing with the non-ASCII character in your name.

**Comment by andreteixeiralopes** [comment]
Perfect, was it!

Thank you very much!
