### ISSUE TITLE
GPU drivers

### ISSUE THREAD

**Issue by YangXS** [niuzhiheng/caffe#32]
Hi zhiheng,

I find that the latest GPU driver for GTX Titan is 340.52  WHQL. Which GPU series is the version 340.62 for ?

Thanks

**Comment by niuzhiheng** [comment]
@YangXS I think the driver 340.62 is together shipped with latest CUDA 6.5. Anyway, the driver 340.52 possibly works the same.

**Comment by YangXS** [comment]
The 340.52 driver with CUDA 6.5 really presents the same running speed as your reported.
Thanks.
