### ISSUE TITLE
CUDA driver is insufficient

### ISSUE THREAD

**Issue by shaikr** [niuzhiheng/caffe#33]
I'm trying to run the net_speed_benchmark on my GPU. After building the solution, when I try to run it, I get the following error: 
"Check failed: error == cudaSuccess (35 vs. 0) CUDA driver version is insufficient for CUDA runtime version"
I installed the 6.5 toolkit. Is there something I'm missing? Certain libs that I should copy anywhere. etc.?
Thanks in advance!

**Comment by niuzhiheng** [comment]
I think probably you have a GPU with low capacity. May I know what GPU you are using?

**Comment by shaikr** [comment]
I'm using tesla k10. Is there a way I could still benchmark this GPU?

**Comment by niuzhiheng** [comment]
The computing capability of K10 is 3.0 which is specified in the property setting of this project. You may refer to #25 and e43879f14165c6abe2fb30ea307e654fb5eb2ce1 for details.

So your GPU should be already supported. You may check your graphic driver to make sure it is 340.xx. And for my case, it is now 340.62. It can be found when you run `nvidia-smi`.

**Comment by shaikr** [comment]
That did it. Thank you very much!
