### ISSUE TITLE
Build problem with VS2012

### ISSUE THREAD

**Issue by Engin007** [niuzhiheng/caffe#41]
I am new to caffe and programming in general. When building I get following Error:

![untitled](https://cloud.githubusercontent.com/assets/9446050/4852192/3cbfb2e6-6079-11e4-828b-30ed05f0d044.png)

what am I doing wrong ?

**Comment by gedditoffme** [comment]
I am getting the same - did you find a solution Engin007?

**Comment by gedditoffme** [comment]
I had another go at this - I found I did not correctly unzip the dependencies. Instead of extracting to the directories within root project, I extracted to a folder "dependency-20140804". Once I copied those files back to the root project folder, it worked.

**Comment by erogol** [comment]
Try to compile in Release mode and be sure you set platform to x64

**Comment by Engin007** [comment]
Exactly @gedditoffme you need to link the appropriate dependencies given by the caffe ported version main site on github. download it, unzip and copy the dependencies to caffe-windows folder you downloaded.
