### ISSUE TITLE
net_speed_benchmark compile fix

### ISSUE THREAD

**Issue by marc40000** [niuzhiheng/caffe#5]
I had to add an

typedef unsigned int uint;

to compile net_speed_benchmark .

**Comment by niuzhiheng** [comment]
Thank you for pointing out this issue. Actually I did not check for each file to ensure successful compilation, especially for the latest merged version.
You may send me a pull request with your fix. Or maybe I will fix this in a future update.

**Comment by niuzhiheng** [comment]
It has been fixed by the [latest update](https://github.com/niuzhiheng/caffe/commit/a879606250ba9b3e377dff0bf988fabb42f0fcfb).

**Comment by marc40000** [comment]
ok great :)
