### ISSUE TITLE
Hi,I can not down load the dependencies when I config the caffe

### ISSUE THREAD

**Issue by xinyaojiejie** [niuzhiheng/caffe#7]
I can not visit the website: http://dl.dropboxusercontent.com/u/3466743/caffe-vs2012/dependency-20140514.7z , I think the reason is the GFW. Could you help to upload these files in this website so that we can download the necessary dependencies?

**Comment by niuzhiheng** [comment]
Hehe, you may download from this [link](http://pan.baidu.com/s/1hqtFoag) instead.

**Comment by xinyaojiejie** [comment]
thank you very much!!
