### ISSUE TITLE
create ImageNet leveldb file fail under windows 7 64bit

### ISSUE THREAD

**Issue by civilman628** [niuzhiheng/caffe#70]
is there anyone create ImageNet levelDB pass under window 7 OS?
on my side its fail.
I can see log file is created, but I do not know how to open it, because it is not txt but some kind of compressed log. is there anyone know how to read this kind of google log?
![capture](https://cloud.githubusercontent.com/assets/8059551/8008274/757369da-0b77-11e5-8431-f610aaad1a64.PNG)

**Comment by ZxYuan** [comment]
Actually you have created the levelDB file. 
In levelDB, a log file (_.log) stores a sequence of recent updates. Each update is appended to the current log file. When the log file reaches a pre-determined size (approximately 4MB by default), it is converted to a sorted table (_.sst) and a new log file is created for future updates.
Please refer to the link below if you'd like to know the format of log files.
https://raw.githubusercontent.com/google/leveldb/master/doc/log_format.txt

**Comment by Dev2022** [comment]
@civilmanxx  I also have the same issue. Have you found how it works? Please let me know how to proceed. Thanks
