### ISSUE TITLE
errors on trying train_lenet.bat

### ISSUE THREAD

**Issue by liguanbin** [niuzhiheng/caffe#8]
Hi, I have successful built the files and generate MainCaller.exe. Then I try train_lenet.bat, it works fine in the cpu mode, however in gpu mode, it fails and the following error comes out?
Could you help me? Thx.
I0624 17:19:24.384238  2980 data_layer.cpp:145] Opening leveldb mnist-train-leve
ldb
F0624 17:19:24.394739  2980 data_layer.cpp:148] Check failed: status.ok() Failed
 to open leveldb mnist-train-leveldb
IO error: mnist-train-leveldb\MANIFEST-000184: The handle is invalid.
**\* Check failure stack trace: ***

**Comment by niuzhiheng** [comment]
Please refer to #2 for a very similar discussion. It is caused probably by another instance running somewhere. You should close your running CPU console window and then start your GPU window.

**Comment by liguanbin** [comment]
Thanks very much for your reply. But the problem still exist with the following error message.

I0624 20:31:33.053694  5588 net.cpp:174] Network initialization done.
I0624 20:31:33.054193  5588 net.cpp:175] Memory required for Data 7882008
I0624 20:31:33.054693  5588 solver.cpp:49] Solver scaffolding done.
I0624 20:31:33.055193  5588 solver.cpp:61] Solving LeNet
I0624 20:31:33.055693  5588 solver.cpp:106] Iteration 0, Testing net
I0624 20:31:33.056193  5588 net.cpp:288] Copying source layer mnist
I0624 20:31:33.056694  5588 net.cpp:288] Copying source layer conv1
I0624 20:31:33.056694  5588 net.cpp:288] Copying source layer pool1
I0624 20:31:33.057193  5588 net.cpp:288] Copying source layer conv2
I0624 20:31:33.057693  5588 net.cpp:288] Copying source layer pool2
I0624 20:31:33.058193  5588 net.cpp:288] Copying source layer ip1
I0624 20:31:33.059193  5588 net.cpp:288] Copying source layer relu1
I0624 20:31:33.059694  5588 net.cpp:288] Copying source layer ip2
I0624 20:31:33.060194  5588 net.cpp:285] Ignoring source layer loss
F0624 20:31:33.064194  5588 im2col.cu:54] Check failed: error == cudaSuccess (8
vs. 0)  invalid device function
**\* Check failure stack trace: ***

**Comment by AlexXieHzZj** [comment]
Please check your video card if match the class of NVIDIA architectures in your vs project configure., for example: GTS 450 , computer_20, sm_20, this project default is computer_35.

**Comment by niuzhiheng** [comment]
See #1 .

**Comment by liguanbin** [comment]
hi, my device is Tesla M2090, and the compute capability version is 2.0,  is it suitable for this project?

**Comment by liguanbin** [comment]
Thanks! I have change the project configure to computer _20, hope it works.
