### ISSUE TITLE
How to compile Caffe for windows without CUDA?

### ISSUE THREAD

**Issue by monjoybme** [niuzhiheng/caffe#85]
Can I compile Caffe for windows without CUDA? looking forward for your kind response.

**Comment by gopi1989** [comment]
Hi monjoy,
From my knowledge it is not possible to built caffe without CUDA.If you want to use caffe without CUDA try in Ubuntu operating system. I did for ubuntu.
Sorry for the late replay.

Regards,
Gopi Krishnan.R

**Comment by monjoybme** [comment]
ok Thank you. I compiled caffe in ubuntu.

_Thanks and Regards,_
_Monjoy Saha_
