### ISSUE TITLE
Hi, How I use google protocol buffer to produce file of caffe.pb.h ?

### ISSUE THREAD

**Issue by xinyaojiejie** [niuzhiheng/caffe#9]
Should I run the protoc.exe in command shell in windows?  I have not use the tools before, Could you help me for it? thank you very mush.

**Comment by xinyaojiejie** [comment]
I have solved the problem yet.

**Comment by jasonustc** [comment]
How to find the file "caffe.pb.h"? I have pulled down all the code, but there is no "proto" folder in "./include/caffe". So when I try to compile the project, an error  "can not open source file "caffe/proto/caffe.pb.h" occurred.  Would you please help me solve this problem?

**Comment by niuzhiheng** [comment]
It will be generated when you compile the code for the first time. You need to download the dependencies and put them in corresponding directories.

**Comment by jasonustc** [comment]
I've solved the problem, thank you very much!
